name: Build and upload to PyPI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
   build_wheels:
     name: Build wheels on ${{ matrix.os }} python ver ${{ matrix.version }}
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
         os: [ubuntu-latest]
         version: [3.7]
     steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Set up Python
       uses: actions/setup-python@v3
       with:
        python-version: '3.7'       
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip build
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi       
     - name: Build wheels
       # uses: pypa/cibuildwheel@v2.5.0
       run: python -m build -n -s -w .
     #- name: Upload packages
     #  uses: pypa/gh-action-pypi-publish@release/v1
     #  with:
     #   user: "rdmitrow"
     #   password: "13579@$^*)Qwe"
     - name: Run unittests
       run:
          pwd
          
          ls -R
          
          pytest
          
     - name: Test with chispa
       run: 
          cd NewBitcoinTrades
          
          python3 BitcoinTradingRun.py TestCase1_dataset_one.csv TestCase1_dataset_two.csv France OutputTestCase1
          
          python3 TestOutput.py OutputTestCase1.csv TestCase1_expected.csv  
     
   Install_wheel:
      name: Install_wheel
      runs-on: ubuntu-latest 
      needs: build_wheels
      steps:
      - name: Install wheel
        # run: python3 -m pip install --index-url https://pypi.org/simple/ --extra-index-url https://pypi.org/simple/ BitcoinTrading_artifact
        run: pip install NewBitcoinTrades
        
#      - name: Run unittests
#        run:
#          pwd
#          ls -R
#          pytest
          
#      - name: Test with chispa
#        run: 
#          python3 BitcoinTradingRun.py TestCase1_dataset_one.csv TestCase1_dataset_two.csv France OutputTestCase1
#          
#          python3 TestOutput.py OutputTestCase1.csv TestCase1_expected.csv     
